---
- hosts: baseinstall
  become: true
  tasks:
    - include: deploy/packages.yml
    - include: deploy/users.yml
    - include: deploy/config.yml
    - include: deploy/install_misc.yml
    - include: deploy/install_asterisk.yml
    - include: deploy/install_asterisk_helpers.yml version={{ conf_version }}
