---
- hosts: prod
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include: find_prod_conf.yml
- hosts: baseinstall
  become: true
  tasks:
    - include: packages.yml
    - include: users.yml
    - include: config.yml
    - include: install_misc.yml
    - include: install_asterisk.yml
    - include: install_asterisk_helpers.yml version={{ conf_version }}
    - include: update_asterisk.yml version={{ conf_version }}
    - include: update_asterisk_sounds.yml
