---
- name: load secrets
  include_vars: "deploy/install_asterisk_helpers_secrets_{{ version }}.yml"
  no_log: true
- name: add logrotate job
  copy:
    src: src/logrotate/logrotate.d/asterisk
    dest: /etc/logrotate.d/asterisk
- name: delete logwatch conf
  file:
    path: /etc/logwatch/conf
    state: absent
- name: copy logwatch conf
  copy:
    src: src/logwatch/conf
    dest: /etc/logwatch
- name: delete logwatch scripts
  file:
    path: /etc/logwatch/scripts
    state: absent
- name: copy logwatch scripts
  copy:
    src: src/logwatch/scripts
    dest: /etc/logwatch
- name: copy logwatch conf which is local or has secrets
  template:
    src: src/logwatch.conf.j2
    dest: /etc/logwatch/conf/logwatch.conf
- name: make futel directory
  file:
    path: /opt/futel
    state: directory
    owner: asterisk
    group: asterisk
- name: make source directory
  file:
    path: /opt/futel/src
    state: directory
    owner: asterisk
    group: asterisk
- name: install event listener
  copy:
    src: src/eventlistener.py
    dest: /opt/futel/src
    owner: asterisk
    group: asterisk
    mode: "a+x"    
- name: install event listener conf which is local or has secrets
  template:
    src: src/eventlistenerconf.py.j2
    dest: /opt/futel/src/eventlistenerconf.py
    owner: asterisk
    group: asterisk
- name: set up supervisord conf
  copy:
    src: src/supervisord.conf
    dest: /etc/supervisord.conf
    owner: root
    group: root
# enable but do not yet start supervisord
- name: enable supervisord service
  service:
    name: supervisord
    enabled: yes
