---
# distro package setup and installation
- name: install selinux bindings, required since we start with selinux
  yum:
    name: libselinux-python
    state: present 
- name: remove yum packages
  yum:
    name:
      #- "@FCoE Storage Client"
      #- "@iSCSI Storage Client"
      #- "2Network file system client"
      #- "@Storage Availability Tools"
      - audit
      - rpcbind
      - selinux-policy
      - selinux-policy-targeted
    state: absent
- name: update yum
  yum:
    name: "*"
    state: latest
- name: copy epel rpm
  copy:
    src: src/epel-release-latest-7.noarch.rpm 
    dest: /tmp/epel-release-latest-7.noarch.rpm 
- name: install epel rpm
  yum:
    name: /tmp/epel-release-latest-7.noarch.rpm
    state: present
- name: install yum packages
  yum:
    name:
      - iptables-services
      - firewalld
      - ntp
      - man
      - vim-enhanced
      - gcc
      - gcc-c++
      - SDL
      - make
      - automake
      - libtool
      - autoconf
      - mlocate
      - lynx
      - cvs
      - git
      - subversion
      - strace
      - ltrace
      - wget
      - lsof
      - tcpdump
      - openssh
      - openssh-server
      - openssh-clients
      - openssl-devel
      - ncurses-devel
      - libxml2-devel
      - lua-devel
      - newt-devel
      - kernel-devel
      - sqlite-devel
      - libuuid-devel
      - festival
      - supervisor
      - logwatch
      - cyrus-sasl-plain
      - python-yaml
      - python-pip
      - redis
      - jansson-devel
    state: present
- name: update pip
  pip:
    name: pip
    state: latest
- name: update pip packages
  pip:
    name:
      - boto3
      - redis
    state: present

