---
- name: copy recordings from prod
  synchronize:
    mode: pull
    src: /opt/asterisk/var/lib/asterisk/sounds/futel/recordings
    dest: tmp/stage
- name: fail if recordings exist on prod
  find:
    paths: '/opt/asterisk/var/lib/asterisk/sounds/futel/recordings'
    file_type: directory
  register: recordings_found
- fail:
     msg: 'The recordings directory is not empty.'
  when: recordings_found.matched > 0
- name: copy voicemail from prod
  synchronize:
    mode: pull
    src: /opt/asterisk/etc/asterisk/vm_futel_users.inc
    dest: tmp/stage
- name: copy voicemail from prod
  synchronize:
    mode: pull
    src: /opt/asterisk/var/spool/asterisk/voicemail/default
    dest: tmp/stage
    delete: yes
- name: copy challenge file from prod
  synchronize:
    mode: pull
    src: /opt/asterisk/etc/asterisk/challenge.csv
    dest: tmp/stage
- name: copy logs from prod
  synchronize:
    mode: pull
    src: /opt/asterisk/var/log/asterisk/messages
    dest: tmp/stage
- name: copy logs from prod
  synchronize:
    mode: pull
    src: /opt/asterisk/var/log/asterisk/metrics
    dest: tmp/stage
- name: copy logs from prod
  synchronize:
    mode: pull
    src: /opt/asterisk/var/log/asterisk/old
    dest: tmp/stage
    delete: yes
