---
- name: load conf
  include_vars: "deploy/conf.yml"
- name: update and copy sounds
  command: ruby scripts/update_audio_assets.rb {{ asterisk_sound_directory }}/{{ item }} {{ asset_directory }}/{{ item }}
  with_items:
    - church-of-robotron
    - longmont
    - oracle-dead-interstitial-long
    - oracle-dead-interstitial-short
    - oracle-dead-oracle
    - recordings/blerg  
    - recordings/karl-oracle-dead
    - recordings/karl_quuux
    - recordings/karl-robotron
    - recordings/karl-voicemail-ivr
    - recordings/karl-wildcard-line
    - recordings/tishbite
    - wildcard-line
    - williams-long
    - williams-short
    
