---
- name: load conf
  include_vars: "conf.yml"
- name: copy asterisk williams short sounds
  copy:
    src: src/var/lib/asterisk/sounds/futel/williams-short
    dest: /opt/asterisk/var/lib/asterisk/sounds/futel
    owner: asterisk
    group: asterisk
- name: copy asterisk williams long sounds
  copy:
    src: src/var/lib/asterisk/sounds/futel/williams-long
    dest: /opt/asterisk/var/lib/asterisk/sounds/futel
    owner: asterisk
    group: asterisk
- name: copy asterisk long oracle sounds
  copy:
    src: src/var/lib/asterisk/sounds/futel/oracle-dead-interstitial-long
    dest: /opt/asterisk/var/lib/asterisk/sounds/futel
    owner: asterisk
    group: asterisk
- name: copy asterisk short oracle sounds
  copy:
    src: src/var/lib/asterisk/sounds/futel/oracle-dead-interstitial-short
    dest: /opt/asterisk/var/lib/asterisk/sounds/futel
    owner: asterisk
    group: asterisk
- name: copy asterisk oracle oracle sounds
  copy:
    src: src/var/lib/asterisk/sounds/futel/oracle-dead-oracle
    dest: /opt/asterisk/var/lib/asterisk/sounds/futel
    owner: asterisk
    group: asterisk
- name: make recordings directory
  file:
    path: /opt/asterisk/var/lib/asterisk/sounds/futel/recordings
    state: directory
    owner: asterisk
    group: asterisk
- name: copy asterisk statement sounds
  copy:
    src: src/var/lib/asterisk/sounds/futel/recordings/karl-oracle-dead
    dest: /opt/asterisk/var/lib/asterisk/sounds/futel/recordings
    owner: asterisk
    group: asterisk
- name: copy asterisk statement sounds
  copy:
    src: src/var/lib/asterisk/sounds/futel/recordings/karl_quuux
    dest: /opt/asterisk/var/lib/asterisk/sounds/futel/recordings
    owner: asterisk
    group: asterisk
- name: copy asterisk statement sounds
  copy:
    src: src/var/lib/asterisk/sounds/futel/recordings/karl-robotron
    dest: /opt/asterisk/var/lib/asterisk/sounds/futel/recordings
    owner: asterisk
    group: asterisk
- name: copy asterisk statement sounds
  copy:
    src: src/var/lib/asterisk/sounds/futel/recordings/karl-voicemail-ivr
    dest: /opt/asterisk/var/lib/asterisk/sounds/futel/recordings
    owner: asterisk
    group: asterisk
- name: copy asterisk statement sounds
  copy:
    src: src/var/lib/asterisk/sounds/futel/recordings/karl-wildcard-line
    dest: /opt/asterisk/var/lib/asterisk/sounds/futel/recordings
    owner: asterisk
    group: asterisk
- name: copy asterisk statement sounds
  copy:
    src: src/var/lib/asterisk/sounds/futel/recordings/tishbite
    dest: /opt/asterisk/var/lib/asterisk/sounds/futel/recordings
    owner: asterisk
    group: asterisk
- name: copy asterisk statement sounds
  copy:
    src: src/var/lib/asterisk/sounds/futel/recordings/blerg
    dest: /opt/asterisk/var/lib/asterisk/sounds/futel/recordings
    owner: asterisk
    group: asterisk
- name: copy asterisk wildcard line sounds
  copy:
    src: src/var/lib/asterisk/sounds/futel/wildcard-line
    dest: /opt/asterisk/var/lib/asterisk/sounds/futel
    owner: asterisk
    group: asterisk
- name: copy sounds
  copy:
    src: "{{ asterisk_sound_directory }}/futel/{{ item }}"
    dest: /opt/asterisk/var/lib/asterisk/sounds/futel
    owner: asterisk
    group: asterisk
  with_items:
    - longmont
    - church-of-robotron
- name: copy asterisk confbridge menu sounds
  copy:
    src: "{{ asterisk_sound_directory }}/en/futelconf"
    dest: /opt/asterisk/var/lib/asterisk/sounds/en
    owner: asterisk
    group: asterisk
- name: copy asterisk hold music
  copy:
    src: src/var/lib/asterisk/moh/hold/
    dest: /opt/asterisk/var/lib/asterisk/moh/hold
    owner: asterisk
    group: asterisk
- name: copy operator hold music
  copy:
    src: src/var/lib/asterisk/moh/operator/
    dest: /opt/asterisk/var/lib/asterisk/moh/operator
    owner: asterisk
    group: asterisk
