---
- name: load conf
  include_vars: "deploy/conf.yml"
- name: clean sounds directories
  file:
    path: "{{ asterisk_sound_directory }}"
    state: absent
- name: clean sounds directories
  file:
    path: "{{ asterisk_sound_directory }}"
    state: directory
- name: update and copy sounds
  command: ruby scripts/update_audio_assets.rb {{ asterisk_sound_directory }}/{{ item }} {{ asset_directory }}/{{ item }}
  with_items:
    - futel/church-of-robotron
    - futel/longmont
    - futel/oracle-dead-interstitial-long
    - futel/oracle-dead-interstitial-short
    - futel/oracle-dead-oracle
    - futel/voyager
    - futel/wildcard-line
    - futel/williams-long
    - futel/williams-short
    - en/statements/blerg
    - en/statements/jodi-voyager
    - en/statements/karl-oracle-dead
    - en/statements/karl_quuux
    - en/statements/karl-robotron
    - en/statements/karl-voicemail-ivr
    - en/statements/karl-wildcard-line
    - en/statements/tishbite
    - en/futelconf
